/**
 * Mirrors `D:\ncr\app\protocols\lock-screen\agent-list.cue` #AgentList /
 * #AgentRow.  Hand-translated for now — will be regenerated by
 * `protocols/codegen/` once the generator lands (view_separation.md D4).
 */

/** status values shared by widget renderer + web. */
export type AgentStatus =
  | 'wip'
  | 'done'
  | 'fail'
  | 'idle'
  | 'stale'   // client-derived: wip + timestamp > threshold
  | 'closed'  // server-derived: cc session closed but status.json wasn't reconciled

export interface AgentRow {
  name: string
  summary: string
  status: AgentStatus
  /** ISO 8601 with offset, e.g. "2026-06-27T10:05:32+09:00". */
  updatedAt: string
  /** MCP server id this agent belongs to (e.g. "main"). */
  serverId: string
}

export interface AgentList {
  agents: AgentRow[]
}
